CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(120) NOT NULL,
    email VARCHAR2(160) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    role VARCHAR2(20) NOT NULL CHECK (role IN ('STUDENT', 'ORGANIZER', 'ADMIN')),
    department VARCHAR2(80),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE events (
    event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id NUMBER NOT NULL REFERENCES users(user_id),
    title VARCHAR2(180) NOT NULL,
    description CLOB,
    category VARCHAR2(30) NOT NULL CHECK (category IN ('TECHNICAL', 'CULTURAL', 'SPORTS', 'WORKSHOP', 'SEMINAR')),
    starts_at TIMESTAMP NOT NULL,
    ends_at TIMESTAMP NOT NULL,
    status VARCHAR2(20) DEFAULT 'DRAFT' NOT NULL CHECK (status IN ('DRAFT', 'PUBLISHED', 'CANCELLED', 'COMPLETED')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT event_time_order CHECK (ends_at > starts_at)
);

CREATE TABLE event_venues (
    venue_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id NUMBER NOT NULL REFERENCES events(event_id),
    venue_name VARCHAR2(120) NOT NULL,
    capacity NUMBER(8) NOT NULL CHECK (capacity > 0),
    UNIQUE (event_id, venue_name)
);

CREATE TABLE registrations (
    registration_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id NUMBER NOT NULL REFERENCES events(event_id),
    student_id NUMBER NOT NULL REFERENCES users(user_id),
    venue_id NUMBER REFERENCES event_venues(venue_id),
    qr_token VARCHAR2(100) NOT NULL UNIQUE,
    status VARCHAR2(20) DEFAULT 'REGISTERED' NOT NULL CHECK (status IN ('REGISTERED', 'ATTENDED', 'CANCELLED')),
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UNIQUE (event_id, student_id)
);

CREATE TABLE check_ins (
    check_in_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id NUMBER NOT NULL UNIQUE REFERENCES registrations(registration_id),
    checked_in_by NUMBER NOT NULL REFERENCES users(user_id),
    venue_id NUMBER NOT NULL REFERENCES event_venues(venue_id),
    checked_in_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE announcements (
    announcement_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id NUMBER NOT NULL REFERENCES users(user_id),
    message VARCHAR2(1000) NOT NULL,
    active_from TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    active_until TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE certificates (
    certificate_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id NUMBER NOT NULL UNIQUE REFERENCES registrations(registration_id),
    certificate_number VARCHAR2(80) NOT NULL UNIQUE,
    file_path VARCHAR2(500),
    issued_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_events_status_start ON events(status, starts_at);
CREATE INDEX idx_registrations_event ON registrations(event_id, status);
CREATE INDEX idx_check_ins_venue ON check_ins(venue_id, checked_in_at);
